name: "💡 Feature Request"
description: "Suggest a new feature or improvement"
labels: ["type: enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: "Describe the feature in detail."
      placeholder: "Explain what the feature is and why it would be useful."
  - type: textarea
    id: use-case
    attributes:
      label: "Use Case"
      description: "How would this feature be used in the game?"
      placeholder: "Describe a situation where this feature would be helpful."
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you considered any alternatives?"
      placeholder: "Describe any other ways this could be implemented."
  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Information"
      description: "Anything else you'd like to add?"
