name: "💡 Feature Request"
description: "Suggest a new feature or improvement"
labels: ["type: enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: "Describe the feature in detail."
      placeholder: "Explain what the feature is and why it would be useful."
  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Information"
      description: "Anything else you'd like to add?"
