blank_issues_enabled: false
contact_links:
  - name: ChunkSpawnerLimiter Discord Server
    url: https://discord.gg/4v9gsBCgg8
    about: Check out additional support on our community discord.
  - name: ChunkSpawnerLimiter Wiki
    url: https://csl.sarhatabaot.net/
    about: Check out our official documentation.